### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by bitcoinuser** [gzuuus/linktr-nostr#1]
Hi,

Thanks for Nostree, it's really good. I would like to share some things that I would like to see.

1- I would like to be able to add a link and at the same time "vote" like or dislike.
2- I would like to be able to see profiles that have some links that I have in my profile.
3- I would like to see stats like: most used links on nostr profiles.

Thanks.

**Comment by gzuuus** [comment]
Hello! thank you for your words and your ideas. At the moment I can't imagine how the interface of vote and downvote would look like, maybe just adding different styles to the buttons? but I want to keep the essence as much as possible, without creating a reddit style client or similar. In the future I will add folders and subfolders for links, maybe you can use it for this.

About the stats yes, I like the idea. I'll be working on it in future iterations.

**Comment by bitcoinuser** [comment]
Yes, maybe my ideas make more sense in a new app. Because I would like to be able to like or dislike a link I add in a list and even allow show users comments in a specific link.

But no problem, your project is great. Thanks.
