### ISSUE TITLE
Cannot remove/edit empty slug

### ISSUE THREAD

**Issue by eko2one** [gzuuus/linktr-nostr#10]
Firefox Version 119.0 (64-bit)

In edit mode I am unable to delete or edit an empty slug.

**Comment by gzuuus** [comment]
Can you reproduce it? i've test it in different devices/browsers but i can do ir properly, with no problem, maybe you can share a screenshot or something?

**Comment by eko2one** [comment]
I cannot reproduce it but here are the screenshots
<img width="426" alt="Screenshot 2023-11-09 at 00 25 23" src="https://github.com/gzuuus/linktr-nostr/assets/92563141/ddc278bc-39a5-4cf2-b2b4-626f31fe567e">
<img width="413" alt="Screenshot 2023-11-09 at 00 27 18" src="https://github.com/gzuuus/linktr-nostr/assets/92563141/066736af-9484-417a-b8ef-780d1a3a6275">

**Comment by gzuuus** [comment]
Its gona be fixed for the next release #11
