### ISSUE TITLE
[Feature] Add support for Nostr Connect NIP-46 remote signer

### ISSUE THREAD

**Issue by eko2one** [gzuuus/linktr-nostr#12]
To enable easy and secure access on mobile devices it would be neat to have additional support for nostr connect nip-46, remote signers, such as https://github.com/nostr-connect/nostrum.

There is also a SDK available: https://github.com/nostr-connect/connect

**Comment by gzuuus** [comment]
Thanks for your suggestion, I will add nip-46 support soon, and will keep this issue open to track its development.

**Comment by gzuuus** [comment]
This is just got merged in #15
