### ISSUE TITLE
Cant add links in mobile view

### ISSUE THREAD

**Issue by drihsanmy** [gzuuus/linktr-nostr#2]
Cant add links in  mobile view. Get undefined error

**Comment by gzuuus** [comment]
Which browser do you use? It should work in any browser that can handle extensions. In my case I can add links from my mobile without problems using android 13, kiwi browser and nos2x.

**Comment by drihsanmy** [comment]
Nostrmo app

**Comment by gzuuus** [comment]
you can use nostromo with nip07 auth? because i dont find the way to do that

**Comment by drihsanmy** [comment]
can

**Comment by gzuuus** [comment]
I see, but dont know how to add a new app to the web utils section. You know how?

**Comment by drihsanmy** [comment]
dont need to. just open the link from any note while using the app.
if you want to add to the webutil can email nostrmo dev
