### ISSUE TITLE
Possible UX/UI Improvements

### ISSUE THREAD

**Issue by NielLiesmons** [gzuuus/linktr-nostr#4]
New List:
1. I would make this a separate button
2. I'd first let the users give the list a Title (and maybe even call it "List Title". Then let them add a Slug (displayed close to the title input field. Then, in a very clearly separated set of input fields let them "Add Links" to that List.
3. The title of the window not remaining "New List" is confusing to me.
4. All Lists should not be there imo and can be separate
5. BUG: when I type a first link + name, then add another and delete that one, suddenly I cannot publish the first one anymore.

Manage Lists:
1. What would be awesome is that on my own profile an edit button would be displayed for each list. Then I can just preview my profile and directly edit where needed
2. Next to that the manage lists button can remain present
3. BUG: for some reason I have to delete lists twice to make them dissapear
4. The pinned-list is a great feature (obvious next step could be to handle the full order of display)

Profile Display:
1. The double use of the @ symbol is a bit confusing for me
2. icon choice, colours, orders, margins etc can all be improved. But those suggestions will be done visually in the Figma https://w3.do/W9asmKy2

**Comment by gzuuus** [comment]
Thanks for the review, I really appreciate it.
About the new list, I think thant I understand properly, but would love to see a mockup on figma to be as clear as possible. 


> BUG: when I type a first link + name, then add another and delete that one, suddenly I cannot publish the first one anymore
That is for validation, you should delete or fill empty fields, if not add button and publish are disabled, 

Already working in edit button for each list in page view
> BUG: for some reason I have to delete lists twice to make them dissapear
If you delete it for the first time its enough, its deleted, if appear again its for delay in response of relays, but its already deleted

> The pinned-list is a great feature (obvious next step could be to handle the full order of display)
Deffinetly, have to think about how to do that 🤔
